import { z } from 'zod';
import { idSchema } from './common';
import { CLOCK_COMMANDS, FOOTBALL_EVENT_KINDS } from '../types/enums';
import {
  MAX_PERIODS,
  MAX_PERIOD_MINUTES,
  MAX_FOOTBALL_SQUAD,
  MAX_PLAYERS_PER_TEAM,
  MIN_PERIODS,
  MIN_PERIOD_MINUTES,
} from '../constants';

/**
 * The football write surface. Three verbs and no more: name the team sheets,
 * move the clock, record an incident.
 */

const lineupEntrySchema = z.object({
  playerId: idSchema,
  /** 0 is the goalkeeper; the rest run back to front through the formation. */
  slot: z.number().int().min(0).max(MAX_PLAYERS_PER_TEAM - 1),
  shirtNumber: z.number().int().min(1).max(99).nullable().default(null),
  isCaptain: z.boolean().default(false),
});

/**
 * Both team sheets, locked in one call — the football twin of playingXiSchema.
 * The squad size is the tournament's rather than a constant, so the length is
 * checked by the API against that tournament rather than here.
 */
export const footballLineupSchema = z.object({
  teams: z
    .array(
      z
        .object({
          teamId: idSchema,
          formation: z
            .string()
            .trim()
            .regex(/^\d+(-\d+){1,3}$/, 'A formation looks like 4-4-2'),
          /** The starting side. Slot 0 is the goalkeeper. */
          players: z
            .array(lineupEntrySchema)
            .min(1)
            .max(MAX_PLAYERS_PER_TEAM)
            .refine(
              (players) => new Set(players.map((p) => p.playerId)).size === players.length,
              'A player cannot appear twice in the lineup',
            )
            .refine(
              (players) => new Set(players.map((p) => p.slot)).size === players.length,
              'Two players cannot occupy the same position',
            )
            .refine(
              (players) => players.filter((p) => p.isCaptain).length <= 1,
              'A side cannot have two captains',
            ),
          /**
           * The bench: everyone in the squad who is not starting. Bounded only
           * by the squad itself — a side that brings twelve to a five-a-side
           * has seven substitutes, and refusing the last two would be the
           * system inventing a rule the sport does not have.
           */
          substitutes: z
            .array(idSchema)
            .max(MAX_FOOTBALL_SQUAD)
            .default([])
            .refine((ids) => new Set(ids).size === ids.length, 'A player cannot be named twice'),
        })
        .refine(
          // Checked here rather than per-array because it is the one rule that
          // spans both: somebody on the pitch cannot also be on the bench.
          (team) =>
            !team.players.some((player) => team.substitutes.includes(player.playerId)),
          {
            message: 'A player cannot start and be a substitute',
            path: ['substitutes'],
          },
        ),
    )
    .length(2, 'Both sides must be named'),
});
export type FootballLineupInput = z.infer<typeof footballLineupSchema>;

/**
 * Kick-off, with the clock the person blowing the whistle actually wants.
 *
 * Both fields are optional and fall back to the tournament's setting. This is
 * the last moment the length of a match can be decided, and it is the right
 * one: the tournament default was set weeks ago by somebody who did not know
 * the pitch would be booked until four.
 */
export const kickOffSchema = z.object({
  periods: z.number().int().min(MIN_PERIODS).max(MAX_PERIODS).optional(),
  periodMinutes: z.number().int().min(MIN_PERIOD_MINUTES).max(MAX_PERIOD_MINUTES).optional(),
});
export type KickOffInput = z.infer<typeof kickOffSchema>;

/**
 * One incident. clientEventId is generated by the scorer's device and is what
 * makes a retry idempotent — the same goal submitted twice is one goal.
 *
 * The minute is deliberately absent: it is stamped by the server from the
 * clock, because a client that supplied its own could put a goal in a minute
 * the match never reached.
 */
export const footballEventSchema = z
  .object({
    clientEventId: z.string().uuid('clientEventId must be a UUID'),
    kind: z.enum(FOOTBALL_EVENT_KINDS),
    teamId: idSchema,
    /** On a substitution, the player coming *on*. */
    playerId: idSchema.nullable().default(null),
    assistPlayerId: idSchema.nullable().default(null),
    /** Substitution only: the player coming off. */
    playerOffId: idSchema.nullable().default(null),
  })
  .refine(
    // Every other incident tolerates "nobody could say who" — a substitution
    // cannot, because it is a statement about two specific people and there is
    // nothing to record without both of them.
    (input) =>
      input.kind !== 'SUBSTITUTION' || (Boolean(input.playerId) && Boolean(input.playerOffId)),
    { message: 'Name both the player coming on and the player going off', path: ['playerOffId'] },
  )
  .refine((input) => !input.playerOffId || input.playerOffId !== input.playerId, {
    message: 'A player cannot replace themselves',
    path: ['playerOffId'],
  });
export type FootballEventRequestInput = z.infer<typeof footballEventSchema>;

/** An undo removes one earlier incident; the original is never deleted. */
export const footballUndoSchema = z.object({
  clientEventId: z.string().uuid(),
  /** Defaults to the most recent standing incident when omitted. */
  targetEventId: idSchema.optional(),
});
export type FootballUndoInput = z.infer<typeof footballUndoSchema>;

export const clockCommandSchema = z.object({
  command: z.enum(CLOCK_COMMANDS),
});
export type ClockCommandInput = z.infer<typeof clockCommandSchema>;
