import { z } from 'zod';
import { idSchema, usernameSchema } from './common';
import { EXTRA_TYPES, TOSS_DECISIONS, WICKET_TYPES } from '../types/enums';
import { PLAYERS_PER_TEAM } from '../constants';

export const generateFixturesSchema = z.object({
  /** Wipes existing fixtures. Refused unless every match is still SCHEDULED. */
  regenerate: z.boolean().default(false),
});
export type GenerateFixturesInput = z.infer<typeof generateFixturesSchema>;

export const updateMatchSchema = z.object({
  /** Dates stay optional forever — fixtures never depend on the calendar. */
  scheduledAt: z.string().datetime().nullable().optional(),
  venue: z.string().trim().max(120).nullable().optional(),
  oversPerInnings: z.number().int().min(1).max(50).optional(),
});
export type UpdateMatchInput = z.infer<typeof updateMatchSchema>;

/**
 * A scorer can be named by id or by handle. In practice an organizer knows
 * "@whynotramaa", not a cuid, so the username path is the one that gets used.
 */
export const assignScorerSchema = z
  .object({
    scorerId: idSchema.optional(),
    username: usernameSchema.optional(),
  })
  .refine((input) => Boolean(input.scorerId || input.username), {
    message: 'Provide either a scorerId or a username',
    path: ['username'],
  });
export type AssignScorerInput = z.infer<typeof assignScorerSchema>;

export const tossSchema = z.object({
  tossWinnerId: idSchema,
  decision: z.enum(TOSS_DECISIONS),
});
export type TossInput = z.infer<typeof tossSchema>;

const xiEntrySchema = z.object({
  playerId: idSchema,
  battingOrder: z.number().int().min(1).max(PLAYERS_PER_TEAM),
  isCaptain: z.boolean().default(false),
  isKeeper: z.boolean().default(false),
});

/**
 * The playing XI for both sides, locked in one call at toss. Exactly eleven
 * per side, exactly one captain, at most one keeper.
 */
export const playingXiSchema = z.object({
  teams: z
    .array(
      z.object({
        teamId: idSchema,
        players: z
          .array(xiEntrySchema)
          .length(PLAYERS_PER_TEAM, `Name exactly ${PLAYERS_PER_TEAM} players`)
          .refine(
            (players) => new Set(players.map((p) => p.playerId)).size === players.length,
            'A player cannot appear twice in the XI',
          )
          .refine(
            (players) => players.filter((p) => p.isCaptain).length === 1,
            'Name exactly one captain',
          )
          .refine(
            (players) => players.filter((p) => p.isKeeper).length <= 1,
            'A side cannot have two wicketkeepers',
          ),
      }),
    )
    .length(2, 'Both sides must be named'),
});
export type PlayingXiInput = z.infer<typeof playingXiSchema>;

/**
 * One delivery. clientEventId is generated by the scorer's device and is what
 * makes a retry idempotent — the same ball submitted twice is one ball.
 */
export const ballSchema = z
  .object({
    clientEventId: z.string().uuid('clientEventId must be a UUID'),
    strikerId: idSchema,
    nonStrikerId: idSchema,
    bowlerId: idSchema,
    runsOffBat: z.number().int().min(0).max(6).default(0),
    extraRuns: z.number().int().min(0).max(10).default(0),
    extraType: z.enum(EXTRA_TYPES).nullable().default(null),
    isWicket: z.boolean().default(false),
    wicketType: z.enum(WICKET_TYPES).nullable().default(null),
    dismissedPlayerId: idSchema.nullable().default(null),
    fielderId: idSchema.nullable().default(null),
  })
  .refine((ball) => ball.strikerId !== ball.nonStrikerId, {
    message: 'The striker and non-striker cannot be the same player',
    path: ['nonStrikerId'],
  });
export type BallRequestInput = z.infer<typeof ballSchema>;

/** A correction supersedes one earlier ball; the original is never removed. */
export const correctionSchema = z.object({
  targetEventId: idSchema,
  replacement: ballSchema,
});
export type CorrectionInput = z.infer<typeof correctionSchema>;

export const undoSchema = z.object({
  clientEventId: z.string().uuid(),
  /** Defaults to the most recent delivery when omitted. */
  targetEventId: idSchema.optional(),
});
export type UndoInput = z.infer<typeof undoSchema>;

export const completeMatchSchema = z.object({
  abandoned: z.boolean().default(false),
  resultText: z.string().trim().max(200).optional(),
});
export type CompleteMatchInput = z.infer<typeof completeMatchSchema>;
