import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import type { MatchDto } from '@howzat/shared';
import { BackLink } from '@/components/ui/BackLink';
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHeader, EmptyState } from '@/components/ui/Card';
import { ErrorText, SkeletonCard } from '@/components/ui/Feedback';
import { StatusPill, TeamMark } from '@/components/ui/Pill';
import { Reveal } from '@/components/ui/Reveal';
import { Sheet } from '@/components/ui/Sheet';
import { ShareLink } from '@/components/ui/ShareLink';
import { useTournament } from '@/features/organizer/queries';
import { cn } from '@/lib/cn';
import { useFixtures, useGenerateFixtures, usePreviewFixtures } from './queries';

/**
 * The schedule.
 *
 * Generation is a two-step — preview, then write — because the write is
 * destructive on a regenerate, and an organizer should see the pairings before
 * committing a league to them.
 */
export function FixturesPage() {
  const { tournamentId = '' } = useParams();

  const tournament = useTournament(tournamentId);
  const fixtures = useFixtures(tournamentId);
  const preview = usePreviewFixtures(tournamentId);
  const generate = useGenerateFixtures(tournamentId);

  const [confirmRegenerate, setConfirmRegenerate] = useState(false);

  const matches = fixtures.data?.items ?? [];
  const hasFixtures = matches.length > 0;
  const started = matches.some((match) => match.status !== 'SCHEDULED');

  async function handleGenerate(regenerate: boolean) {
    await generate.mutateAsync(regenerate);
    preview.reset();
    setConfirmRegenerate(false);
  }

  if (tournament.isPending) return <SkeletonCard rows={4} />;
  if (tournament.error) return <ErrorText error={tournament.error} />;
  if (!tournament.data) return null;

  return (
    <div className="flex flex-col gap-12">
      <div className="flex flex-col gap-8">
        <BackLink to={`/tournaments/${tournamentId}`}>{tournament.data.name}</BackLink>

        <div className="flex flex-wrap items-end justify-between gap-x-10 gap-y-5">
          <div>
            <p className="eyebrow">Schedule</p>
            <h1 className="serif mt-4 text-[2.5rem] text-primary sm:text-[3rem]">Fixtures</h1>
            <p className="mt-3 max-w-xl text-secondary">
              {hasFixtures
                ? `${matches.length} match${matches.length === 1 ? '' : 'es'} — every pair meets ${
                    tournament.data.doubleRoundRobin ? 'twice, home and away' : 'exactly once'
                  }.`
                : 'Generated by the circle method: no dates, no venues, every pair exactly once.'}
            </p>
          </div>

          <div className="flex flex-wrap gap-2.5">
            <ShareLink
              slug={tournamentId}
              url={`${window.location.origin}/tournament/${tournamentId}`}
              label="Share tournament"
              matchLabel={tournament.data.name}
              variant="quiet"
            />
            {!hasFixtures ? (
              <>
                <Button
                  variant="secondary"
                  isLoading={preview.isPending}
                  onClick={() => preview.mutate()}
                >
                  Preview the draw
                </Button>
                <Button isLoading={generate.isPending} onClick={() => void handleGenerate(false)}>
                  Generate fixtures
                </Button>
              </>
            ) : (
              <Button
                variant="secondary"
                disabled={started}
                onClick={() => setConfirmRegenerate(true)}
              >
                {started ? 'A match has already started' : 'Regenerate'}
              </Button>
            )}
          </div>
        </div>

        <div className="rule" />
      </div>

      {preview.error ? <ErrorText error={preview.error} /> : null}
      {generate.error ? <ErrorText error={generate.error} /> : null}

      {/* The dry run, discarded the moment fixtures are written. */}
      {preview.data && !hasFixtures ? (
        <Card>
          <CardHeader className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="eyebrow">Preview</p>
              <p className="mt-2 text-[0.9375rem] text-secondary">
                {preview.data.totalMatches} matches — nothing has been saved yet.
              </p>
            </div>
            <Button isLoading={generate.isPending} onClick={() => void handleGenerate(false)}>
              Looks right — generate
            </Button>
          </CardHeader>

          <CardBody className="flex flex-col gap-8">
            {preview.data.rounds.map((round) => (
              <div key={round.round}>
                <p className="eyebrow mb-4">Round {round.round}</p>
                <ul className="flex flex-col gap-2.5">
                  {round.matches.map((match) => (
                    <li
                      key={`${match.home.id}-${match.away.id}`}
                      className="flex items-center gap-3 text-[0.9375rem] text-primary"
                    >
                      {match.home.name}
                      <span className="mono text-[0.6875rem] text-muted">v</span>
                      {match.away.name}
                    </li>
                  ))}
                </ul>
              </div>
            ))}

            {preview.data.playoffs.length > 0 ? (
              <div className="border-t border-line pt-7">
                <p className="eyebrow mb-4">Playoffs</p>
                <ul className="flex flex-col gap-2.5">
                  {preview.data.playoffs.map((slot) => (
                    <li key={slot.stage} className="text-[0.9375rem]">
                      <span className="font-medium text-primary">{slot.label}</span>
                      <span className="text-muted"> — {slot.description}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </CardBody>
        </Card>
      ) : null}

      {fixtures.isPending ? (
        <SkeletonCard rows={3} />
      ) : fixtures.error ? (
        <ErrorText error={fixtures.error} />
      ) : hasFixtures ? (
        <RoundList matches={matches} />
      ) : (
        <EmptyState
          title="No fixtures on the board yet"
          description="Once every registered side has exactly eleven players, generate the draw and the matches will appear here."
          action={
            <Button isLoading={generate.isPending} onClick={() => void handleGenerate(false)}>
              Generate fixtures
            </Button>
          }
        />
      )}

      <Sheet
        open={confirmRegenerate}
        onClose={() => setConfirmRegenerate(false)}
        title="Regenerate the whole draw?"
        description="Every fixture in this tournament is replaced. Only possible while no match has started."
        footer={
          <>
            <Button
              variant="danger"
              isLoading={generate.isPending}
              onClick={() => void handleGenerate(true)}
            >
              Replace the fixtures
            </Button>
            <Button variant="quiet" onClick={() => setConfirmRegenerate(false)}>
              Keep them
            </Button>
          </>
        }
      >
        <p className="text-secondary">
          Scorer assignments on the current fixtures go with them. The circle method is
          deterministic, so the same sides will produce the same draw.
        </p>
      </Sheet>
    </div>
  );
}

function RoundList({ matches }: { matches: MatchDto[] }) {
  const rounds = [...new Set(matches.map((match) => match.round))].sort((a, b) => a - b);

  return (
    <div className="flex flex-col gap-12">
      {rounds.map((round, roundIndex) => {
        const inRound = matches.filter((match) => match.round === round);
        const isPlayoff = inRound.every((match) => match.stage !== 'LEAGUE');

        return (
          <section key={round} className="flex flex-col gap-5">
            <div className="flex items-center gap-5">
              <p className="eyebrow shrink-0">{isPlayoff ? 'Playoffs' : `Round ${round}`}</p>
              <span aria-hidden className="h-px flex-1 bg-line" />
              <p className="mono shrink-0 text-[0.6875rem] text-muted">
                {inRound.length} match{inRound.length === 1 ? '' : 'es'}
              </p>
            </div>

            <div className="flex flex-col gap-3">
              {inRound.map((match, index) => (
                <Reveal key={match.id} index={roundIndex * 2 + index} step={40}>
                  <MatchRow match={match} />
                </Reveal>
              ))}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function MatchRow({ match }: { match: MatchDto }) {
  const primaryLabel =
    match.status === 'SCHEDULED'
      ? 'Set up the match'
      : match.status === 'LIVE' || match.status === 'INNINGS_BREAK'
        ? 'Continue scoring'
        : 'Match details';

  return (
    <article
      className={cn(
        'flex flex-col gap-5 rounded-[var(--radius-lg)] border border-line bg-raised p-6 sm:p-7',
        'transition-colors duration-[var(--dur)] hover:border-line-strong',
        // A live match gets a brass edge — the one row you are looking for.
        match.status === 'LIVE' && 'border-[var(--accent-line)]',
      )}
    >
      <div className="flex flex-wrap items-start justify-between gap-x-6 gap-y-4">
        <div className="min-w-0">
          <Link to={`/matches/${match.id}`} className="group flex flex-wrap items-center gap-3">
            <Side team={match.team1} />
            <span className="mono text-[0.6875rem] text-muted">v</span>
            <Side team={match.team2} />
          </Link>

          <p className="mono mt-3 text-[0.6875rem] tracking-[0.06em] text-muted uppercase">
            {match.stage === 'LEAGUE' ? `Round ${match.round}` : match.stage.replace(/_/g, ' ')}
            <span className="mx-2 text-line-strong">·</span>
            {match.oversPerInnings} overs
            {match.scorers.length > 0 ? (
              <>
                <span className="mx-2 text-line-strong">·</span>
                scorer {match.scorers.map((scorer) => `@${scorer.username}`).join(', ')}
              </>
            ) : null}
          </p>
        </div>

        <StatusPill status={match.status} />
      </div>

      {match.resultText ? (
        <div className="flex flex-wrap items-center gap-3">
          <p className="serif text-lg text-primary">{match.resultText}</p>
          <a href={`/live/${match.publicSlug}?view=scorecard`} target="_blank" rel="noreferrer">
            <Button size="sm" variant="quiet">View scorecard</Button>
          </a>
        </div>
      ) : null}

      <div className="flex flex-wrap items-center gap-2.5 border-t border-line pt-5">
        <Link to={`/matches/${match.id}`}>
          <Button size="sm" variant={match.status === 'SCHEDULED' ? 'primary' : 'secondary'}>
            {primaryLabel}
          </Button>
        </Link>

        <a href={`/live/${match.publicSlug}`} target="_blank" rel="noreferrer">
          <Button size="sm" variant="quiet">
            Live card ↗
          </Button>
        </a>

        <ShareLink
          slug={match.publicSlug}
          variant="quiet"
          matchLabel={`${match.team1?.shortName ?? 'TBD'} v ${match.team2?.shortName ?? 'TBD'}`}
        />
      </div>
    </article>
  );
}

function Side({ team }: { team: MatchDto['team1'] }) {
  if (!team) {
    return (
      <span className="text-[1.0625rem] text-muted italic">To be decided</span>
    );
  }

  return (
    <span className="flex items-center gap-2.5">
      <TeamMark shortName={team.shortName} color={team.primaryColor} size="sm" />
      <span className="text-[1.0625rem] font-medium text-primary underline decoration-transparent underline-offset-4 transition-colors group-hover:decoration-[var(--accent-strong)]">
        {team.name}
      </span>
    </span>
  );
}
